export const HOUSE_ACTIVITIES: Object = [
    "cleaning, sweeping carpet or floors, general",
    "cleaning, sweeping, slow, light effort",
    "cleaning, sweeping, slow, moderate effort",
    "cleaning, heavy or major (e.g. wash car, wash windows), moderate effort",
    "cleaning, mopping, standing, moderate effort",
    "cleaning windows, washing windows, general",
    "mopping, standing, light effort",
    "polishing floors, standing, walking slowly, using electric polishing machine",
    "multiple household tasks all at once, light effort",
    "multiple household tasks all at once, moderate effort",
    "multiple household tasks all at once, vigorous effort",
    "cleaning, house or cabin, general, moderate effort",
    "dusting or polishing furniture, general",
    "kitchen activity (cooking, washing dishes, cleaning up), moderate effort",
    "cleaning, straightening up, changing linen, carrying out trash",
    "wash dishes, standing",
    "wash dishes, clearing dishes from table, walking, light effort",
    "vacuuming, general, moderate effort",
    "butchering animals, small",
    "butchering animal, large, vigorous effort",
    "cutting and smoking fish, drying fish or meat",
    "tanning hides, general",
    "cooking or food preparation, moderate effort",
    "cooking or food preparation – standing or sitting, manual appliances",
    "serving food, setting table, implied walking or standing",
    "cooking or food preparation, walking",
    "feeding household animals",
    "putting away groceries",
    "carrying groceries upstairs",
    "cooking Indian bread on an outside stove",
    "food shopping with or without a grocery cart, standing or walking",
    "non-food shopping, with or without a cart, standing or walking",
    "ironing",
    "knitting, sewing, light effort, wrapping presents, sitting",
    "sewing with a machine",
    "laundry, fold or hang clothes",
    "laundry, hanging wash, washing clothes by hand, moderate effort",
    "laundry, putting away clothes, gathering clothes to pack, putting away laundry",
    "making bed, changing linens",
    "maple syruping/sugar bushing (including carrying buckets, carrying wood)",
    "moving furniture, household items, carrying boxes",
    "moving, lifting light loads",
    "organizing room",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, moderate effort",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, light effort",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, vigorous effort",
    "sweeping garage, sidewalk or outside of house",
    "standing, packing/unpacking boxes,  loading or unloading items in car",
    "implied walking, putting away household items, moderate effort",
    "lying quietly and watching television",
    "lying quietly, doing nothing, lying in bed awake, listening to music",
    "sitting quietly and watching television",
    "sitting quietly, general",
    "sitting quietly, fidgeting, general, fidgeting hands",
    "sitting, fidgeting feet",
    "sitting, smoking",
    "sitting, listening to music or watching a movie in a theater",
    "sitting at a desk, resting head in hands",
    "sleeping",
    "standing quietly, standing in a line",
    "standing, fidgeting",
    "reclining, writing",
    "reclining, talking or talking on phone",
    "reclining, reading",
    "meditating",
    "mowing lawn, walk, power mower, moderate or vigorous effort",
    "raking lawn or leaves, moderate effort",
    "sacking grass, leaves",
    "shoveling dirt or mud",
    "shoveling snow, by hand, moderate effort",
    "shoveling snow, by hand ( 610)",
    "shoveling snow, by hand, vigorous effort",
    "trimming shrubs or trees, manual cutter",
    "trimming shrubs or trees, using leaf blower, edger",
    "walking, applying fertilizer or seeding a lawn, push applicator",
    "watering lawn or garden, standing or walking",
    "weeding, cultivating garden, light-to-moderate effort",
    "weeding, cultivating garden ( 580)",
    "weeding, cultivating garden, using a hoe, moderate-to-vigorous effort",
    "gardening, general, moderate effort",
    "picking fruit off trees, picking fruits/vegetables, moderate effort",
    "picking vegatables or fruit off trees",
    "implied walking/standing – picking up yard, light, picking flowers or vegetables",
    "walking, gathering gardening tools",
    "wheelbarrow, pushing garden cart or wheelbarrow",
    "yard work, general, light effort",
    "yard work, general, moderate effort",
    "yard work, general, vigorous effort"
];

export const SPORTS_ACTIVITIES: Object = [
    "archery, non-hunting",
    "badminton, competitive ( 450)",
    "badminton, social singles and doubles, general",
    "basketball, game ( 490)",
    "basketball, non-game, general ( 480)",
    "basketball, general",
    "basketball, officiating ( 500)",
    "basketball, shooting baskets",
    "basketball, drills, practice",
    "basketball, wheelchair",
    "billiards",
    "bowling ( 390)",
    "bowling, indoor, bowling alley",
    "boxing, in ring, general",
    "boxing, punching bag",
    "boxing, sparring",
    "broomball",
    "childrens games, hopscotch, 4-square, dodgeball,  tetherball",
    "cheerleading, gymnastic moves, competitive",
    "coaching, football, soccer, basketball, baseball, swimming, etc.",
    "coaching, actively playing sport with players",
    "cricket, batting, bowling, fielding",
    "croquet",
    "curling",
    "darts, wall or lawn",
    "drag racing, pushing or driving a car",
    "auto racing, open wheel",
    "fencing",
    "football, competitive",
    "football, touch, flag, general ( 510)",
    "football, touch, flag, light effort",
    "football or baseball, playing catch",
    "frisbee playing, general",
    "frisbee, ultimate",
    "golf, general",
    "golf, walking, carrying clubs",
    "golf, miniature, driving range",
    "golf, walking, pulling clubs",
    "golf, using power cart ( 070)",
    "gymnastics, general",
    "hacky sack",
    "handball, general ( 520)",
    "handball, team",
    "high ropes course, multiple elements",
    "hang gliding",
    "hockey, field",
    "hockey, ice, general",
    "hockey, ice, competitive",
    "horseback riding, general",
    "horse chores, feeding, watering, cleaning stalls",
    "saddling, cleaning, grooming, harnessing and unharnessing horse",
    "horseback riding, trotting",
    "horseback riding, canter or gallop",
    "horseback riding,walking",
    "horseback riding, jumping",
    "horse cart, driving, standing or sitting",
    "horseshoe pitching, quoits",
    "jai alai",
    "martial arts, slower pace, novice performers, practice",
    "martial arts, moderate pace (judo, jujitsu, karate, kick boxing, tae kwan do)",
    "juggling",
    "kickball",
    "lacrosse",
    "lawn bowling, bocce ball, outdoor",
    "moto-cross, off-road motor sports, all-terrain vehicle, general",
    "orienteering",
    "paddleball, competitive",
    "paddleball, casual, general ",
    "polo, on horseback",
    "racquetball, competitive",
    "racquetball, general",
    "rock or mountain climbing ",
    "rock climbing, ascending rock, high difficulty",
    "rock climbing, ascending or traversing rock, low-to-moderate difficulty",
    "rock climbing, rappelling",
    "rodeo sports, general, light effort",
    "rodeo sports, general, moderate effort",
    "rodeo sports, general, vigorous effort",
    "rope jumping, fast pace, 120-160 skips/min",
    "rope jumping, moderate pace, 100-120 skips/min, 2 foot skip, plain bounce",
    "rope jumping under 100 skips/min, 2 foot skip, rhythm bounce",
    "rugby, union, team, competitive",
    "rugby, touch, non-competitive",
    "shuffleboard",
    "skateboarding, general, moderate effort",
    "skateboarding, competitive, vigorous effort",
    "skating, roller",
    "rollerblading, in-line skating, 14.4 km/h (9.0 mph), recreational pace",
    "rollerblading, in-line skating, 17.7 km/h (11.0 mph)",
    "rollerblading, in-line skating, 21.0 to 21.7 km/h (13.0 to 13.6 mph)",
    "rollerblading, in-line skating, 24.0 km/h (15.0 mph), maximal effort",
    "skydiving, base jumping, bungee jumping",
    "soccer, competitive",
    "soccer, casual, general ",
    "softball or baseball, fast or slow pitch, general ",
    "softball, practice",
    "softball, officiating",
    "softball,pitching",
    "sports spectator, very excited, emotional, physically moving",
    "squash ",
    "squash, general",
    "table tennis, ping pong ",
    "tai chi, qi gong, general",
    "tai chi, qi gong, sitting, light effort",
    "tennis, general",
    "tennis, doubles ",
    "tennis, doubles",
    "tennis, singles ",
    "tennis, hitting balls, non-game play, moderate effort",
    "trampoline, recreational",
    "trampoline, competitive",
    "volleyball ",
    "volleyball, competitive, in gymnasium",
    "volleyball, non-competitive, 6 – 9 member team, general",
    "volleyball, beach, in sand",
    "wrestling (one match = 5 minutes)",
    "wallyball, general",
    "track and field (e.g., shot, discus, hammer throw)",
    "track and field (e.g., high jump, long jump, triple jump, javelin, pole vault)",
    "track and field (e.g., steeplechase, hurdles)",
    "hunting, hiking with hunting gear",
    "pistol shooting or trap shooting, standing",
    "rifle exercises, shooting, lying down",
    "rifle exercises, shooting, kneeling or standing",
    "jog/walk combination (jogging component of less than 10 minutes) ( 180)",
    "jogging, general",
    "jogging, in place",
    "jogging, on a mini-tramp",
    "Running, 4 mph (13 min/mile)",
    "running, 5 mph (12 min/mile)",
    "running, 5.2 mph (11.5 min/mile)",
    "running, 6 mph (10 min/mile)",
    "running, 6.7 mph (9 min/mile)",
    "running, 7 mph (8.5 min/mile)",
    "running, 7.5 mph (8 min/mile)",
    "running, 8 mph (7.5 min/mile)",
    "running, 8.6 mph (7 min/mile)",
    "running, 9 mph (6.5 min/mile)",
    "running, 10 mph (6 min/mile)",
    "running, 11 mph (5.5 min/mile)",
    "running, 12 mph (5 min/mile)",
    "running, 13 mph (4.6 min/mile)",
    "running, 14 mph (4.3 min/mile)",
    "running, cross country",
    "running, ( 200)",
    "running, stairs, up",
    "running, on a track, team practice",
    "running, training, pushing a wheelchair or baby carrier",
    "running, marathon",
    "bicycling, mountain, uphill, vigorous",
    "bicycling, mountain, competitive, racing",
    "bicycling, BMX",
    "bicycling, mountain, general",
    "bicycling,  under 10 mph, leisure, to work or for pleasure",
    "bicycling, to/from work, self selected pace",
    "bicycling, on dirt or farm road, moderate pace",
    "bicycling, general",
    "bicycling, leisure, 5.5 mph",
    "bicycling, leisure, 9.4 mph",
    "bicycling, 10-11.9 mph, leisure, slow, light effort",
    "bicycling, 12-13.9 mph, leisure, moderate effort",
    "bicycling, 14-15.9 mph, racing or leisure, fast, vigorous effort",
    "bicycling, 16-19 mph not drafting or over 19 mph drafting",
    "bicycling over 20 mph, racing, not drafting",
    "bicycling, 12 mph, seated, hands on brake hoods or bar drops, 80 rpm",
    "bicycling, 12 mph, standing, hands on brake hoods, 60 rpm",
    "backpacking ",
    "backpacking, hiking or organized walking with a daypack",
    "carrying 15 pound load (e.g. suitcase), level ground or downstairs",
    "hiking, cross country ",
    "hiking or walking at a normal pace through fields and hillsides",
    "bird watching, slow walk",
    "marching, moderate speed, military, no pack",
    "marching rapidly, military, no pack",
    "pushing or pulling stroller, 2.5 to 3.1 mph",
    "pushing a wheelchair, non-occupational",
    "race walking",
    "stair climbing, using or climbing up ladder ",
    "stair climbing, slow pace",
    "stair climbing, fast pace",
    "using crutches",
    "walking, for exercise, 5.0 mph, with ski poles, Nordic walking, level, fast pace",
    "walking, for exercise, with ski poles, Nordic walking, uphill",
    "walking, backwards, 3.5 mph, level",
    "walking, backwards, 3.5 mph, uphill, 5% grade",
    "boating, power, driving",
    "boating, power, passenger, light",
    "canoeing, on camping trip ",
    "canoeing, harvesting wild rice, knocking rice off the stalks",
    "canoeing, portaging",
    "canoeing, rowing, 2.0-3.9 mph, light effort",
    "canoeing, rowing, 4.0-5.9 mph, moderate effort",
    "canoeing, rowing, kayaking, competition,  over 6 mph, vigorous effort",
    "canoeing, rowing, for pleasure, general ",
    "canoeing, rowing, in competition, or crew or sculling ",
    "diving, springboard or platform",
    "kayaking, moderate effort",
    "paddle boat",
    "sailing, boat and board sailing, windsurfing, ice sailing, general ",
    "sailing, in competition",
    "sailing, Sunfish/Laser/Hobby Cat, Keel boats, ocean sailing, yachting, leisure",
    "skiing, water or wakeboarding ",
    "jet skiing, driving, in water",
    "skindiving, fast",
    "skindiving, moderate",
    "skindiving, scuba diving, general ",
    "snorkeling",
    "surfing, body or board, general",
    "surfing, body or board, competitive",
    "paddle boarding, standing",
    "swimming laps, freestyle, fast, vigorous effort",
    "swimming laps, freestyle, front crawl, slow, light or moderate effort",
    "swimming, backstroke, general, training or competition",
    "swimming, backstroke, recreational",
    "swimming, breaststroke, general, training or competition",
    "swimming, breaststroke, recreational",
    "swimming, butterfly, general",
    "swimming, crawl, fast speed, ~75 yards/minute, vigorous effort",
    "swimming, crawl, medium speed, ~50 yards/minute, vigorous effort",
    "swimming, lake, ocean, river ",
    "swimming, leisurely, not lap swimming, general",
    "swimming, sidestroke, general",
    "swimming, synchronized",
    "swimming, treading water, fast, vigorous effort",
    "swimming, treading water, moderate effort, general",
    "tubing, floating on a river, general",
    "water aerobics, water calisthenics",
    "water polo",
    "water volleyball",
    "water jogging",
    "water walking, light effort, slow pace",
    "water walking, moderate effort, moderate pace",
    "water walking, vigorous effort, brisk pace",
    "whitewater rafting, kayaking, or canoeing",
    "windsurfing, not pumping for speed",
    "windsurfing or kitesurfing, crossing trial",
    "windsurfing, competition, pumping for speed",
    "dog sledding, mushing",
    "dog sledding, passenger",
    "moving ice house, set up/drill holes",
    "ice fishing, sitting",
    "skating, ice dancing",
    "skating, ice, 9 mph or less",
    "skating, ice, general ( 360)",
    "skating, ice, rapidly, more than 9 mph, not competitive",
    "skating, speed, competitive",
    "ski jumping, climb up carrying skis",
    "skiing, general",
    "skiing, cross country, 2.5 mph, slow or light effort, ski walking",
    "skiing, cross country, 4.0-4.9 mph, moderate speed and effort, general",
    "skiing, cross country, 5.0-7.9 mph, brisk speed, vigorous effort",
    "skiing, cross country, over 8.0 mph, elite skier, racing",
    "skiing, cross country, hard snow, uphill, maximum, snow mountaineering",
    "skiing, cross-country, skating",
    "skiing, cross-country, biathlon, skating technique",
    "skiing, downhill, alpine or snowboarding, light effort, active time only",
    "skiing, downhill, alpine or snowboarding, moderate effort",
    "skiing, downhill, vigorous effort, racing",
    "skiing, roller, elite racers",
    "sledding, tobogganing, bobsledding, luge ",
    "snow shoeing, moderate effort",
    "snow shoeing, vigorous effort",
    "snowmobiling, driving, moderate",
    "snowmobiling, passenger"
];