export const HOUSE_ACTIVITIES: Object = [
    "cleaning, sweeping carpet or floors, general",
    "cleaning, sweeping, slow, light effort",
    "cleaning, sweeping, slow, moderate effort",
    "cleaning, heavy or major (e.g. wash car, wash windows), moderate effort",
    "cleaning, mopping, standing, moderate effort",
    "cleaning windows, washing windows, general",
    "mopping, standing, light effort",
    "polishing floors, standing, walking slowly, using electric polishing machine",
    "multiple household tasks all at once, light effort",
    "multiple household tasks all at once, moderate effort",
    "multiple household tasks all at once, vigorous effort",
    "cleaning, house or cabin, general, moderate effort",
    "dusting or polishing furniture, general",
    "kitchen activity (cooking, washing dishes, cleaning up), moderate effort",
    "cleaning, straightening up, changing linen, carrying out trash",
    "wash dishes, standing",
    "wash dishes, clearing dishes from table, walking, light effort",
    "vacuuming, general, moderate effort",
    "butchering animals, small",
    "butchering animal, large, vigorous effort",
    "cutting and smoking fish, drying fish or meat",
    "tanning hides, general",
    "cooking or food preparation, moderate effort",
    "cooking or food preparation – standing or sitting, manual appliances",
    "serving food, setting table, implied walking or standing",
    "cooking or food preparation, walking",
    "feeding household animals",
    "putting away groceries",
    "carrying groceries upstairs",
    "cooking Indian bread on an outside stove",
    "food shopping with or without a grocery cart, standing or walking",
    "non-food shopping, with or without a cart, standing or walking",
    "ironing",
    "knitting, sewing, light effort, wrapping presents, sitting",
    "sewing with a machine",
    "laundry, fold or hang clothes",
    "laundry, hanging wash, washing clothes by hand, moderate effort",
    "laundry, putting away clothes, gathering clothes to pack, putting away laundry",
    "making bed, changing linens",
    "maple syruping/sugar bushing (including carrying buckets, carrying wood)",
    "moving furniture, household items, carrying boxes",
    "moving, lifting light loads",
    "organizing room",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, moderate effort",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, light effort",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, vigorous effort",
    "sweeping garage, sidewalk or outside of house",
    "standing, packing/unpacking boxes,  loading or unloading items in car",
    "implied walking, putting away household items, moderate effort",
    "lying quietly and watching television",
    "lying quietly, doing nothing, lying in bed awake, listening to music",
    "sitting quietly and watching television",
    "sitting quietly, general",
    "sitting quietly, fidgeting, general, fidgeting hands",
    "sitting, fidgeting feet",
    "sitting, smoking",
    "sitting, listening to music or watching a movie in a theater",
    "sitting at a desk, resting head in hands",
    "sleeping",
    "standing quietly, standing in a line",
    "standing, fidgeting",
    "reclining, writing",
    "reclining, talking or talking on phone",
    "reclining, reading",
    "meditating",
    "mowing lawn, walk, power mower, moderate or vigorous effort",
    "raking lawn or leaves, moderate effort",
    "sacking grass, leaves",
    "shoveling dirt or mud",
    "shoveling snow, by hand, moderate effort",
    "shoveling snow, by hand ( 610)",
    "shoveling snow, by hand, vigorous effort",
    "trimming shrubs or trees, manual cutter",
    "trimming shrubs or trees, using leaf blower, edger",
    "walking, applying fertilizer or seeding a lawn, push applicator",
    "watering lawn or garden, standing or walking",
    "weeding, cultivating garden, light-to-moderate effort",
    "weeding, cultivating garden ( 580)",
    "weeding, cultivating garden, using a hoe, moderate-to-vigorous effort",
    "gardening, general, moderate effort",
    "picking fruit off trees, picking fruits/vegetables, moderate effort",
    "picking vegatables or fruit off trees",
    "implied walking/standing – picking up yard, light, picking flowers or vegetables",
    "walking, gathering gardening tools",
    "wheelbarrow, pushing garden cart or wheelbarrow",
    "yard work, general, light effort",
    "yard work, general, moderate effort",
    "yard work, general, vigorous effort"
];

export const SPORTS_ACTIVITIES: Object = [
    "archery, non-hunting",
    "badminton, competitive ( 450)",
    "badminton, social singles and doubles, general",
    "basketball, game ( 490)",
    "basketball, non-game, general ( 480)",
    "basketball, general",
    "basketball, officiating ( 500)",
    "basketball, shooting baskets",
    "basketball, drills, practice",
    "basketball, wheelchair",
    "billiards",
    "bowling ( 390)",
    "bowling, indoor, bowling alley",
    "boxing, in ring, general",
    "boxing, punching bag",
    "boxing, sparring",
    "broomball",
    "childrens games, hopscotch, 4-square, dodgeball,  tetherball",
    "cheerleading, gymnastic moves, competitive",
    "coaching, football, soccer, basketball, baseball, swimming, etc.",
    "coaching, actively playing sport with players",
    "cricket, batting, bowling, fielding",
    "croquet",
    "curling",
    "darts, wall or lawn",
    "drag racing, pushing or driving a car",
    "auto racing, open wheel",
    "fencing",
    "football, competitive",
    "football, touch, flag, general ( 510)",
    "football, touch, flag, light effort",
    "football or baseball, playing catch",
    "frisbee playing, general",
    "frisbee, ultimate",
    "golf, general",
    "golf, walking, carrying clubs",
    "golf, miniature, driving range",
    "golf, walking, pulling clubs",
    "golf, using power cart ( 070)",
    "gymnastics, general",
    "hacky sack",
    "handball, general ( 520)",
    "handball, team",
    "high ropes course, multiple elements",
    "hang gliding",
    "hockey, field",
    "hockey, ice, general",
    "hockey, ice, competitive",
    "horseback riding, general",
    "horse chores, feeding, watering, cleaning stalls",
    "saddling, cleaning, grooming, harnessing and unharnessing horse",
    "horseback riding, trotting",
    "horseback riding, canter or gallop",
    "horseback riding,walking",
    "horseback riding, jumping",
    "horse cart, driving, standing or sitting",
    "horseshoe pitching, quoits",
    "jai alai",
    "martial arts, slower pace, novice performers, practice",
    "martial arts, moderate pace (judo, jujitsu, karate, kick boxing, tae kwan do)",
    "juggling",
    "kickball",
    "lacrosse",
    "lawn bowling, bocce ball, outdoor",
    "moto-cross, off-road motor sports, all-terrain vehicle, general",
    "orienteering",
    "paddleball, competitive",
    "paddleball, casual, general ",
    "polo, on horseback",
    "racquetball, competitive",
    "racquetball, general",
    "rock or mountain climbing ",
    "rock climbing, ascending rock, high difficulty",
    "rock climbing, ascending or traversing rock, low-to-moderate difficulty",
    "rock climbing, rappelling",
    "rodeo sports, general, light effort",
    "rodeo sports, general, moderate effort",
    "rodeo sports, general, vigorous effort",
    "rope jumping, fast pace, 120-160 skips/min",
    "rope jumping, moderate pace, 100-120 skips/min, 2 foot skip, plain bounce",
    "rope jumping under 100 skips/min, 2 foot skip, rhythm bounce",
    "rugby, union, team, competitive",
    "rugby, touch, non-competitive",
    "shuffleboard",
    "skateboarding, general, moderate effort",
    "skateboarding, competitive, vigorous effort",
    "skating, roller",
    "rollerblading, in-line skating, 14.4 km/h (9.0 mph), recreational pace",
    "rollerblading, in-line skating, 17.7 km/h (11.0 mph)",
    "rollerblading, in-line skating, 21.0 to 21.7 km/h (13.0 to 13.6 mph)",
    "rollerblading, in-line skating, 24.0 km/h (15.0 mph), maximal effort",
    "skydiving, base jumping, bungee jumping",
    "soccer, competitive",
    "soccer, casual, general ",
    "softball or baseball, fast or slow pitch, general ",
    "softball, practice",
    "softball, officiating",
    "softball,pitching",
    "sports spectator, very excited, emotional, physically moving",
    "squash ",
    "squash, general",
    "table tennis, ping pong ",
    "tai chi, qi gong, general",
    "tai chi, qi gong, sitting, light effort",
    "tennis, general",
    "tennis, doubles ",
    "tennis, doubles",
    "tennis, singles ",
    "tennis, hitting balls, non-game play, moderate effort",
    "trampoline, recreational",
    "trampoline, competitive",
    "volleyball ",
    "volleyball, competitive, in gymnasium",
    "volleyball, non-competitive, 6 – 9 member team, general",
    "volleyball, beach, in sand",
    "wrestling (one match = 5 minutes)",
    "wallyball, general",
    "track and field (e.g., shot, discus, hammer throw)",
    "track and field (e.g., high jump, long jump, triple jump, javelin, pole vault)",
    "track and field (e.g., steeplechase, hurdles)",
    "hunting, hiking with hunting gear",
    "pistol shooting or trap shooting, standing",
    "rifle exercises, shooting, lying down",
    "rifle exercises, shooting, kneeling or standing",
    "jog/walk combination (jogging component of less than 10 minutes) ( 180)",
    "jogging, general",
    "jogging, in place",
    "jogging, on a mini-tramp",
    "Running, 4 mph (13 min/mile)",
    "running, 5 mph (12 min/mile)",
    "running, 5.2 mph (11.5 min/mile)",
    "running, 6 mph (10 min/mile)",
    "running, 6.7 mph (9 min/mile)",
    "running, 7 mph (8.5 min/mile)",
    "running, 7.5 mph (8 min/mile)",
    "running, 8 mph (7.5 min/mile)",
    "running, 8.6 mph (7 min/mile)",
    "running, 9 mph (6.5 min/mile)",
    "running, 10 mph (6 min/mile)",
    "running, 11 mph (5.5 min/mile)",
    "running, 12 mph (5 min/mile)",
    "running, 13 mph (4.6 min/mile)",
    "running, 14 mph (4.3 min/mile)",
    "running, cross country",
    "running, ( 200)",
    "running, stairs, up",
    "running, on a track, team practice",
    "running, training, pushing a wheelchair or baby carrier",
    "running, marathon",
    "bicycling, mountain, uphill, vigorous",
    "bicycling, mountain, competitive, racing",
    "bicycling, BMX",
    "bicycling, mountain, general",
    "bicycling,  under 10 mph, leisure, to work or for pleasure",
    "bicycling, to/from work, self selected pace",
    "bicycling, on dirt or farm road, moderate pace",
    "bicycling, general",
    "bicycling, leisure, 5.5 mph",
    "bicycling, leisure, 9.4 mph",
    "bicycling, 10-11.9 mph, leisure, slow, light effort",
    "bicycling, 12-13.9 mph, leisure, moderate effort",
    "bicycling, 14-15.9 mph, racing or leisure, fast, vigorous effort",
    "bicycling, 16-19 mph not drafting or over 19 mph drafting",
    "bicycling over 20 mph, racing, not drafting",
    "bicycling, 12 mph, seated, hands on brake hoods or bar drops, 80 rpm",
    "bicycling, 12 mph, standing, hands on brake hoods, 60 rpm",
    "backpacking ",
    "backpacking, hiking or organized walking with a daypack",
    "carrying 15 pound load (e.g. suitcase), level ground or downstairs",
    "hiking, cross country ",
    "hiking or walking at a normal pace through fields and hillsides",
    "bird watching, slow walk",
    "marching, moderate speed, military, no pack",
    "marching rapidly, military, no pack",
    "pushing or pulling stroller, 2.5 to 3.1 mph",
    "pushing a wheelchair, non-occupational",
    "race walking",
    "stair climbing, using or climbing up ladder ",
    "stair climbing, slow pace",
    "stair climbing, fast pace",
    "using crutches",
    "walking, for exercise, 5.0 mph, with ski poles, Nordic walking, level, fast pace",
    "walking, for exercise, with ski poles, Nordic walking, uphill",
    "walking, backwards, 3.5 mph, level",
    "walking, backwards, 3.5 mph, uphill, 5% grade",
    "boating, power, driving",
    "boating, power, passenger, light",
    "canoeing, on camping trip ",
    "canoeing, harvesting wild rice, knocking rice off the stalks",
    "canoeing, portaging",
    "canoeing, rowing, 2.0-3.9 mph, light effort",
    "canoeing, rowing, 4.0-5.9 mph, moderate effort",
    "canoeing, rowing, kayaking, competition,  over 6 mph, vigorous effort",
    "canoeing, rowing, for pleasure, general ",
    "canoeing, rowing, in competition, or crew or sculling ",
    "diving, springboard or platform",
    "kayaking, moderate effort",
    "paddle boat",
    "sailing, boat and board sailing, windsurfing, ice sailing, general ",
    "sailing, in competition",
    "sailing, Sunfish/Laser/Hobby Cat, Keel boats, ocean sailing, yachting, leisure",
    "skiing, water or wakeboarding ",
    "jet skiing, driving, in water",
    "skindiving, fast",
    "skindiving, moderate",
    "skindiving, scuba diving, general ",
    "snorkeling",
    "surfing, body or board, general",
    "surfing, body or board, competitive",
    "paddle boarding, standing",
    "swimming laps, freestyle, fast, vigorous effort",
    "swimming laps, freestyle, front crawl, slow, light or moderate effort",
    "swimming, backstroke, general, training or competition",
    "swimming, backstroke, recreational",
    "swimming, breaststroke, general, training or competition",
    "swimming, breaststroke, recreational",
    "swimming, butterfly, general",
    "swimming, crawl, fast speed, ~75 yards/minute, vigorous effort",
    "swimming, crawl, medium speed, ~50 yards/minute, vigorous effort",
    "swimming, lake, ocean, river ",
    "swimming, leisurely, not lap swimming, general",
    "swimming, sidestroke, general",
    "swimming, synchronized",
    "swimming, treading water, fast, vigorous effort",
    "swimming, treading water, moderate effort, general",
    "tubing, floating on a river, general",
    "water aerobics, water calisthenics",
    "water polo",
    "water volleyball",
    "water jogging",
    "water walking, light effort, slow pace",
    "water walking, moderate effort, moderate pace",
    "water walking, vigorous effort, brisk pace",
    "whitewater rafting, kayaking, or canoeing",
    "windsurfing, not pumping for speed",
    "windsurfing or kitesurfing, crossing trial",
    "windsurfing, competition, pumping for speed",
    "dog sledding, mushing",
    "dog sledding, passenger",
    "moving ice house, set up/drill holes",
    "ice fishing, sitting",
    "skating, ice dancing",
    "skating, ice, 9 mph or less",
    "skating, ice, general ( 360)",
    "skating, ice, rapidly, more than 9 mph, not competitive",
    "skating, speed, competitive",
    "ski jumping, climb up carrying skis",
    "skiing, general",
    "skiing, cross country, 2.5 mph, slow or light effort, ski walking",
    "skiing, cross country, 4.0-4.9 mph, moderate speed and effort, general",
    "skiing, cross country, 5.0-7.9 mph, brisk speed, vigorous effort",
    "skiing, cross country, over 8.0 mph, elite skier, racing",
    "skiing, cross country, hard snow, uphill, maximum, snow mountaineering",
    "skiing, cross-country, skating",
    "skiing, cross-country, biathlon, skating technique",
    "skiing, downhill, alpine or snowboarding, light effort, active time only",
    "skiing, downhill, alpine or snowboarding, moderate effort",
    "skiing, downhill, vigorous effort, racing",
    "skiing, roller, elite racers",
    "sledding, tobogganing, bobsledding, luge ",
    "snow shoeing, moderate effort",
    "snow shoeing, vigorous effort",
    "snowmobiling, driving, moderate",
    "snowmobiling, passenger"
];

export const WORK_ACTIVITIES: Object = [
    "active workstation, treadmill desk, walking",
    "airline flight attendant",
    "bakery, general, moderate effort",
    "bakery, light effort",
    "bookbinding",
    "building road, driving heavy machinery",
    "building road, directing traffic, standing",
    "carpentry, general, light effort",
    "carpentry, general, moderate effort",
    "carpentry, general, heavy or vigorous effort",
    "carrying heavy loads (e.g., bricks, tools)",
    "carrying moderate loads up stairs, moving boxes 25-49 lbs",
    "chambermaid, hotel housekeeper, making bed, cleaning bathroom, pushing cart",
    "coal mining, drilling coal, rock",
    "coal mining, erecting supports",
    "coal mining, general",
    "coal mining, shoveling coal",
    "cook, chef",
    "construction, outside, remodeling, new structures",
    "custodial work, light effort ",
    "custodial work, moderate effort ",
    "electrical work (e.g., hook up wire, tapping-splicing)",
    "engineer (e.g., mechanical or electrical)",
    "farming, vigorous effort (e.g., baling hay, cleaning barn)",
    "farming, feeding animals, chasing cattle by walking/horseback, harvesting crops",
    "farming, light effort (e.g., cleaning animal sheds, preparing animal feed)",
    "farming, driving tasks (e.g., driving tractor or harvester)",
    "farming, feeding small animals",
    "farming, feeding cattle, horses",
    "farming, hauling water ",
    "farming, taking care of animals (grooming, brushing, shearing sheep, branding)",
    "farming, rice, planting, grain milling activities",
    "farming, milking by hand, cleaning pails, moderate effort",
    "farming, milking by machine, light effort",
    "fire fighter, general",
    "fire fighter, rescue victim, automobile accident, using pike pole",
    "fire fighter, raising and climbing ladder with full gear, simulated fire supression",
    "fire fighter, hauling hoses, carrying equipment, breaking down walls",
    "fishing, commercial, light effort",
    "fishing, commercial, moderate effort",
    "fishing, commercial, vigorous effort",
    "forestry, ax chopping,1.25 kg axe, 51 blows/min",
    "forestry, ax chopping, slow, 1.25 kg axe, 19 blows/min, moderate effort",
    "forestry, ax chopping, fast, 1.25 kg axe, 35 blows/min, vigorous effort",
    "forestry, moderate effort (sawing wood with power saw, weeding, hoeing)",
    "forestry,  barking, felling, trimming, carrying or stacking logs, planting, sawing",
    "furriery",
    "garbage collector, walking, dumping bins into truck",
    "hairstylist (e.g., plaiting hair, manicure, make-up artist)",
    "horse grooming, including feeding, cleaning stalls, bathing, brushing, clipping",
    "horse, feeding, watering, cleaning stalls, implied walking and lifting loads",
    "horse racing, galloping",
    "horse racing, trotting",
    "horse racing, walking",
    "kitchen maid",
    "lawn keeper, yard work, general",
    "laundry worker",
    "locksmith",
    "machine tooling, working sheet metal, machine fitter, operating lathe, welding",
    "Machine tooling, operating punch press, moderate effort",
    "manager, property",
    "manual or unskilled labor, general, light effort",
    "manual or unskilled labor, general, moderate effort",
    "manual or unskilled labor, general, vigorous effort",
    "masonry, concrete, moderate effort",
    "masonry, concrete, light effort",
    "massage therapist, standing",
    "moving, carrying or pushing heavy objects, 75 lbs or more,",
    "skindiving or SCUBA diving as a frogman, Navy Seal",
    "operating heavy duty equipment, automated, not driving",
    "orange grove work, picking fruit",
    "painting,house, furniture, moderate effort",
    "plumbing activities",
    "printing, paper industry worker, standing",
    "police, directing traffic, standing",
    "police, driving a squad car, sitting",
    "police, riding in a squad car, sitting",
    "police, making an arrest, standing",
    "postal carrier, walking to deliver mail",
    "shoe repair, general",
    "shoveling, digging ditches",
    "shoveling, more than 16 lbs/minute, deep digging, vigorous effort",
    "shoveling, less than 10 lbs/minute, moderate effort",
    "shoveling, 10 to 15 lbs/minute, vigorous effort",
    "sitting tasks, light effort office work, chemistry lab work, computer work",
    "sitting meetings",
    "sitting tasks, moderate effort (e.g., pushing heavy levers)",
    "sitting, teaching stretching or yoga, or light effort exercise class",
    "standing tasks, light effort (bartending, store clerk)",
    "standing assemble heavy parts, welding, stocking parts, nursing patient care",
    "standing lifting items continuously, 10 to 20 lbs, with limited walking or resting",
    "standing, moderate effort, intermittent lifting 50 lbs, hitch/twisting ropes",
    "standing, lifting more than 50 lbs, masonry, painting, paper hanging",
    "steel mill, moderate effort (e.g., fettling, forging, tipping molds)",
    "steel mill, hand rolling, merchant mill rolling, removing slag, tending furnace",
    "tailoring, cutting fabric",
    "tailoring, general",
    "tailoring, hand sewing",
    "tailoring, machine sewing",
    "tailoring, pressing",
    "tailoring, weaving, finishing operations, washing, dyeing",
    "tailoring, weaving, spinning and weaving operations",
    "truck driving, loading and unloading truck, tying down load",
    "Truch, driving delivery truck, taxi, shuttlebus, school bus",
    "typing, electric, manual or computer",
    "using heavy power tools such as pneumatic tools (e.g., jackhammers, drills)",
    "using heavy tools (not power) such as shovel, pick, tunnel bar, spade",
    "walking on job, less than 2.0 mph, very slow speed, in office or lab area",
    "walking on job, 3.0 mph, in office, moderate speed, not carrying anything",
    "walking on job, 3.5 mph, in office, brisk speed, not carrying anything",
    "walking on job, 2.5 mph, slow speed and carrying light objects less than 25 lbs",
    "walking, gathering things at work, ready to leave",
    "walking, 2.5 mph, slow speed, carrying heavy objects more than 25 lbs",
    "walking, 3.0 mph, moderately and carrying light objects less than 25 lbs",
    "walking, pushing a wheelchair",
    "walking, 3.5 mph, briskly and carrying objects less than 25 lbs",
    "walking or walk downstairs or standing, carrying objects about 25 to 49 lbs",
    "walking or walk downstairs or standing, carrying objects about 50 to 74 lbs",
    "walking or walk downstairs or standing, carrying objects about 75 to 99 lbs",
    "walking or walk downstairs or standing, carrying objects about 100 lbs or more",
    "working in scene shop, theater actor, backstage employee"
];

export const GYM_ACTIVITIES = [
    "resistance training, vigorous – weight lifting, power lifting or body building",
    "resistance training, squats , slow or explosive effort",
    "resistance training, multiple exercises, 8-15 repetitions at varied resistance",
    "circuit training, moderate effort",
    "circuit training, including kettlebells with minimal rest and vigorous intensity",
    "Curves exercise routines in women",
    "health club exercise classes",
    "health club exercise, conditioning classes",
    "aerobic, step, with 6 – 8 inch step",
    "aerobic, step, with 10 – 12 inch step",
    "aerobic, step, with 4-inch step",
    "bench step class, general",
    "aerobic, low impact",
    "aerobic, high impact",
    "aerobic dance wearing 10-15 lb weights",
    "walking, 2.5 mph, level, firm surface",
    "walking, 2.5 mph, downhill",
    "walking, 2.8 to 3.2 mph, level, moderate pace, firm surface",
    "walking, 3.5 mph, level, brisk, firm surface, walking for exercise",
    "walking, 2.9 to 3.5 mph, uphill, 1 to 5% grade",
    "walking, 2.9 to 3.5 mph, uphill, 6% to 15% grade",
    "walking, 4.0 mph, level, firm surface, very brisk pace",
    "walking, 4.5 mph, level, firm surface, very, very brisk",
    "walking, 5.0 mph, level, firm surface",
    "walking, 5.0 mph, uphill, 3% grade",
    "Running, 4 mph (13 min/mile)",
    "running, 5 mph (12 min/mile)",
    "running, 5.2 mph (11.5 min/mile)",
    "running, 6 mph (10 min/mile)",
    "running, 6.7 mph (9 min/mile)",
    "running, 7 mph (8.5 min/mile)",
    "running, 7.5 mph (8 min/mile)",
    "running, 8 mph (7.5 min/mile)",
    "running, 8.6 mph (7 min/mile)",
    "running, 9 mph (6.5 min/mile)",
    "running, 10 mph (6 min/mile)",
    "running, 11 mph (5.5 min/mile)",
    "running, 12 mph (5 min/mile)",
    "running, 13 mph (4.6 min/mile)",
    "running, 14 mph (4.3 min/mile)",
    "rowing, stationary ergometer, general, vigorous effort",
    "rowing, stationary, general, moderate effort",
    "rowing, stationary, 100 watts, moderate effort",
    "rowing, stationary, 150 watts, vigorous effort",
    "rowing, stationary, 200 watts, very vigorous effort",
    "bicycling, stationary, general",
    "bicycling, stationary, 30-50 watts, very light to light effort",
    "bicycling, stationary, 90-100 watts, moderate to vigorous effort",
    "bicycling, stationary, 101-160 watts, vigorous effort",
    "bicycling, stationary, 161-200 watts, vigorous effort",
    "bicycling, stationary, 201-270 watts, very vigorous effort",
    "bicycling, stationary, 51-89 watts, light-to-moderate effort",
    "bicycling, stationary, RPM/Spin bike class",
    "Elliptical trainer, moderate effort",
    "swimming laps, freestyle, fast, vigorous effort",
    "swimming laps, freestyle, front crawl, slow, light or moderate effort",
    "swimming, backstroke, general, training or competition",
    "swimming, backstroke, recreational",
    "swimming, breaststroke, general, training or competition",
    "swimming, breaststroke, recreational",
    "swimming, butterfly, general",
    "swimming, crawl, fast speed, ~75 yards/minute, vigorous effort",
    "swimming, crawl, medium speed, ~50 yards/minute, vigorous effort",
    "swimming, leisurely, not lap swimming, general",
    "swimming, sidestroke, general",
    "swimming, treading water, fast, vigorous effort",
    "swimming, treading water, moderate effort, general",
    "rope jumping, fast pace, 120-160 skips/min",
    "rope jumping, moderate pace, 100-120 skips/min, 2 foot skip, plain bounce",
    "rope jumping under 100 skips/min, 2 foot skip, rhythm bounce",
    "calisthenics (e.g., push ups, sit ups, pull-ups, jumping jacks), vigorous effort",
    "calisthenics (e.g., push ups, sit ups, pull-ups, lunges), moderate effort",
    "calisthenics (e.g., situps, abdominal crunches), light effort",
    "calisthenics, light or moderate effort",
    "home exercise, general",
    "stair-treadmill ergometer, general",
    "rope skipping, general",
    "ski machine, general",
    "slide board exercise, general",
    "slimnastics, jazzercise",
    "stretching, mild",
    "pilates, general",
    "teaching exercise class (e.g., aerobic, water)",
    "therapeutic exercise ball, Fitball exercise",
    "upper body exercise, arm ergometer",
    "upper body exercise, Airdyne (arms only) 40 rpm, moderate",
    "water aerobics, water calisthenics, water exercise",
    "whirlpool, sitting",
    "video exercise workouts, (e.g., yoga, stretching), light effort",
    "video exercise workouts, moderate effort",
    "video exercise workouts, cardio-resistance, vigorous effort",
    "yoga, Hatha",
    "yoga, Power",
    "yoga, Nadisodhana",
    "yoga, Surya Namaskar",
    "Haka Powhiri, Moteatea, Waita Tira, Whakawatea, moderate effort",
    "Haka, Taiahab, vigorous effort",
    "basketball, game ( 490)",
    "basketball, non-game, general ( 480)",
    "basketball, general",
    "basketball, shooting baskets",
    "basketball, drills, practice",
    "boxing, in ring, general",
    "boxing, punching bag",
    "boxing, sparring",
    "handball, general ( 520)",
    "handball, team",
    "martial arts, slower pace, novice performers, practice",
    "martial arts, moderate pace (judo, jujitsu, karate, kick boxing, tae kwan do)",
    "tai chi, qi gong, general",
    "tai chi, qi gong, sitting, light effort",
    "volleyball, competitive, in gymnasium",
    "volleyball, non-competitive, 6 – 9 member team, general"
];