export const HOUSE_ACTIVITIES: Object = [
    "cleaning, sweeping carpet or floors, general",
    "cleaning, sweeping, slow, light effort",
    "cleaning, sweeping, slow, moderate effort",
    "cleaning, heavy or major (e.g. wash car, wash windows), moderate effort",
    "cleaning, mopping, standing, moderate effort",
    "cleaning windows, washing windows, general",
    "mopping, standing, light effort",
    "polishing floors, standing, walking slowly, using electric polishing machine",
    "multiple household tasks all at once, light effort",
    "multiple household tasks all at once, moderate effort",
    "multiple household tasks all at once, vigorous effort",
    "cleaning, house or cabin, general, moderate effort",
    "dusting or polishing furniture, general",
    "kitchen activity (cooking, washing dishes, cleaning up), moderate effort",
    "cleaning, straightening up, changing linen, carrying out trash",
    "wash dishes, standing",
    "wash dishes, clearing dishes from table, walking, light effort",
    "vacuuming, general, moderate effort",
    "butchering animals, small",
    "butchering animal, large, vigorous effort",
    "cutting and smoking fish, drying fish or meat",
    "tanning hides, general",
    "cooking or food preparation, moderate effort",
    "cooking or food preparation – standing or sitting, manual appliances",
    "serving food, setting table, implied walking or standing",
    "cooking or food preparation, walking",
    "feeding household animals",
    "putting away groceries",
    "carrying groceries upstairs",
    "cooking Indian bread on an outside stove",
    "food shopping with or without a grocery cart, standing or walking",
    "non-food shopping, with or without a cart, standing or walking",
    "ironing",
    "knitting, sewing, light effort, wrapping presents, sitting",
    "sewing with a machine",
    "laundry, fold or hang clothes",
    "laundry, hanging wash, washing clothes by hand, moderate effort",
    "laundry, putting away clothes, gathering clothes to pack, putting away laundry",
    "making bed, changing linens",
    "maple syruping/sugar bushing (including carrying buckets, carrying wood)",
    "moving furniture, household items, carrying boxes",
    "moving, lifting light loads",
    "organizing room",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, moderate effort",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, light effort",
    "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, vigorous effort",
    "sweeping garage, sidewalk or outside of house",
    "standing, packing/unpacking boxes,  loading or unloading items in car",
    "implied walking, putting away household items, moderate effort",
    "lying quietly and watching television",
    "lying quietly, doing nothing, lying in bed awake, listening to music",
    "sitting quietly and watching television",
    "sitting quietly, general",
    "sitting quietly, fidgeting, general, fidgeting hands",
    "sitting, fidgeting feet",
    "sitting, smoking",
    "sitting, listening to music or watching a movie in a theater",
    "sitting at a desk, resting head in hands",
    "sleeping",
    "standing quietly, standing in a line",
    "standing, fidgeting",
    "reclining, writing",
    "reclining, talking or talking on phone",
    "reclining, reading",
    "meditating",
    "mowing lawn, walk, power mower, moderate or vigorous effort",
    "raking lawn or leaves, moderate effort",
    "sacking grass, leaves",
    "shoveling dirt or mud",
    "shoveling snow, by hand, moderate effort",
    "shoveling snow, by hand ( 610)",
    "shoveling snow, by hand, vigorous effort",
    "trimming shrubs or trees, manual cutter",
    "trimming shrubs or trees, using leaf blower, edger",
    "walking, applying fertilizer or seeding a lawn, push applicator",
    "watering lawn or garden, standing or walking",
    "weeding, cultivating garden, light-to-moderate effort",
    "weeding, cultivating garden ( 580)",
    "weeding, cultivating garden, using a hoe, moderate-to-vigorous effort",
    "gardening, general, moderate effort",
    "picking fruit off trees, picking fruits/vegetables, moderate effort",
    "picking vegatables or fruit off trees",
    "implied walking/standing – picking up yard, light, picking flowers or vegetables",
    "walking, gathering gardening tools",
    "wheelbarrow, pushing garden cart or wheelbarrow",
    "yard work, general, light effort",
    "yard work, general, moderate effort",
    "yard work, general, vigorous effort"
];